spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: '5672'

# docker run -d --name my-rabbit -p 5672:5672 -p 15672:15672 rabbitmq:management-alpine
# access http://localhost:15672/#/